/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.*;

/**
 *
 * @author Medical School
 */
public class mainWindow extends javax.swing.JFrame {

    /**
     * Creates new form mainWindow
     */
    public mainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        caledoniaLabel = new javax.swing.JLabel();
        studentsListScrollPane = new javax.swing.JScrollPane();
        studentsList = new javax.swing.JList<>();
        studentsLabel = new javax.swing.JLabel();
        studentInfoPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        referenceIDLabel = new javax.swing.JLabel();
        editStudentDataButton = new javax.swing.JButton();
        deleteStudentButton = new javax.swing.JButton();
        notesLabel = new javax.swing.JLabel();
        reportsListSP = new javax.swing.JScrollPane();
        reportsList = new javax.swing.JList<>();
        noteCreateButton = new javax.swing.JButton();
        noteDeleteButton = new javax.swing.JButton();
        reportCreateButton = new javax.swing.JButton();
        reportDeleteButton = new javax.swing.JButton();
        notesListSP = new javax.swing.JScrollPane();
        notesList = new javax.swing.JList<>();
        reportsLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        entryTitleLabel = new javax.swing.JLabel();
        entryTitleField = new javax.swing.JTextField();
        entryAuthorLabel = new javax.swing.JLabel();
        entryAuthorField = new javax.swing.JTextField();
        entryContentLabel = new javax.swing.JLabel();
        ecfSP = new javax.swing.JScrollPane();
        entryContentField = new javax.swing.JEditorPane();
        viewerWindowLabel = new javax.swing.JLabel();
        exportButton = new javax.swing.JButton();
        createStudentButton = new javax.swing.JButton();
        assignmentManagerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        caledoniaLabel.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        caledoniaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        caledoniaLabel.setText("caledonia");

        studentsList.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        studentsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        studentsList.setName(""); // NOI18N
        studentsListScrollPane.setViewportView(studentsList);
        DefaultListCellRenderer SL_renderer =  (DefaultListCellRenderer)studentsList.getCellRenderer();
        SL_renderer.setHorizontalAlignment(JLabel.CENTER);

        studentsLabel.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        studentsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        studentsLabel.setText("Students");

        studentInfoPanel.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        nameLabel.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel.setText("First Name, Last Name");

        referenceIDLabel.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        referenceIDLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        referenceIDLabel.setText("Reference ID: $ID");

        editStudentDataButton.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        editStudentDataButton.setText("Edit Student Data");
        editStudentDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editStudentDataButtonActionPerformed(evt);
            }
        });

        deleteStudentButton.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        deleteStudentButton.setText("Delete Student");
        deleteStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteStudentButtonActionPerformed(evt);
            }
        });

        notesLabel.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        notesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        notesLabel.setText("Notes");

        reportsList.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        reportsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        reportsListSP.setViewportView(reportsList);
        DefaultListCellRenderer RL_renderer =  (DefaultListCellRenderer)reportsList.getCellRenderer();
        RL_renderer.setHorizontalAlignment(JLabel.CENTER);

        noteCreateButton.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        noteCreateButton.setText("+");
        noteCreateButton.setToolTipText("Create a new note.");
        noteCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noteCreateButtonActionPerformed(evt);
            }
        });

        noteDeleteButton.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        noteDeleteButton.setText("-");
        noteDeleteButton.setToolTipText("Remove a note.");
        noteDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noteDeleteButtonActionPerformed(evt);
            }
        });

        reportCreateButton.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        reportCreateButton.setText("+");
        reportCreateButton.setToolTipText("Generate a new report based off notes.");
        reportCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportCreateButtonActionPerformed(evt);
            }
        });

        reportDeleteButton.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        reportDeleteButton.setText("-");
        reportDeleteButton.setToolTipText("Remove an old report.");
        reportDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportDeleteButtonActionPerformed(evt);
            }
        });

        notesList.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        notesList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        notesListSP.setViewportView(notesList);
        DefaultListCellRenderer NL_renderer =  (DefaultListCellRenderer)notesList.getCellRenderer();
        NL_renderer.setHorizontalAlignment(JLabel.CENTER);

        reportsLabel.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        reportsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reportsLabel.setText("Reports");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        entryTitleLabel.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        entryTitleLabel.setText("Title");

        entryTitleField.setEditable(false);
        entryTitleField.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        entryTitleField.setText("Title");

        entryAuthorLabel.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        entryAuthorLabel.setText("Author");

        entryAuthorField.setEditable(false);
        entryAuthorField.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        entryAuthorField.setText("Author");

        entryContentLabel.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        entryContentLabel.setText("Content");

        entryContentField.setEditable(false);
        ecfSP.setViewportView(entryContentField);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(ecfSP, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(entryTitleField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(entryAuthorField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(entryTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(entryAuthorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(entryContentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(entryTitleLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(entryTitleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(entryAuthorLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(entryAuthorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(entryContentLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ecfSP, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                                .addContainerGap())
        );

        viewerWindowLabel.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        viewerWindowLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewerWindowLabel.setText("Viewer Window");

        exportButton.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        exportButton.setText("Export Content");
        exportButton.setToolTipText("");
        exportButton.setEnabled(false);
        exportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout studentInfoPanelLayout = new javax.swing.GroupLayout(studentInfoPanel);
        studentInfoPanel.setLayout(studentInfoPanelLayout);
        studentInfoPanelLayout.setHorizontalGroup(
                studentInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(studentInfoPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(studentInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(referenceIDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(studentInfoPanelLayout.createSequentialGroup()
                                                .addGroup(studentInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(notesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(notesListSP, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(studentInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(reportsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(reportsListSP, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addGroup(studentInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(viewerWindowLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addComponent(deleteStudentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(editStudentDataButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(studentInfoPanelLayout.createSequentialGroup()
                                                .addComponent(noteCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(noteDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(reportCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(reportDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(exportButton, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        studentInfoPanelLayout.setVerticalGroup(
                studentInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(studentInfoPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(nameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(referenceIDLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(studentInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(notesLabel)
                                        .addGroup(studentInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(reportsLabel)
                                                .addComponent(viewerWindowLabel)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(studentInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(reportsListSP)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(notesListSP))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(studentInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(studentInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(reportCreateButton)
                                                .addComponent(reportDeleteButton)
                                                .addComponent(noteDeleteButton)
                                                .addComponent(exportButton))
                                        .addComponent(noteCreateButton, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addComponent(deleteStudentButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editStudentDataButton)
                                .addContainerGap())
        );

        createStudentButton.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        createStudentButton.setText("Create Student");
        createStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createStudentButtonActionPerformed(evt);
            }
        });

        assignmentManagerButton.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        assignmentManagerButton.setText("Manage Assignments");
        assignmentManagerButton.setToolTipText("Coming soon!");
        assignmentManagerButton.setEnabled(false);
        assignmentManagerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignmentManagerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(caledoniaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(studentsListScrollPane)
                                        .addComponent(studentsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(createStudentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(assignmentManagerButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(studentInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(caledoniaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(studentsLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(studentsListScrollPane)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(createStudentButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(assignmentManagerButton)
                                .addContainerGap())
                        .addComponent(studentInfoPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void deleteStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void noteCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void assignmentManagerButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void createStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void noteDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void reportCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void reportDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void editStudentDataButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void exportButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton assignmentManagerButton;
    private javax.swing.JLabel caledoniaLabel;
    private javax.swing.JButton createStudentButton;
    private javax.swing.JButton deleteStudentButton;
    private javax.swing.JScrollPane ecfSP;
    private javax.swing.JButton editStudentDataButton;
    private javax.swing.JTextField entryAuthorField;
    private javax.swing.JLabel entryAuthorLabel;
    private javax.swing.JEditorPane entryContentField;
    private javax.swing.JLabel entryContentLabel;
    private javax.swing.JTextField entryTitleField;
    private javax.swing.JLabel entryTitleLabel;
    private javax.swing.JButton exportButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton noteCreateButton;
    private javax.swing.JButton noteDeleteButton;
    private javax.swing.JLabel notesLabel;
    private javax.swing.JList<String> notesList;
    private javax.swing.JScrollPane notesListSP;
    private javax.swing.JLabel referenceIDLabel;
    private javax.swing.JButton reportCreateButton;
    private javax.swing.JButton reportDeleteButton;
    private javax.swing.JLabel reportsLabel;
    private javax.swing.JList<String> reportsList;
    private javax.swing.JScrollPane reportsListSP;
    private javax.swing.JPanel studentInfoPanel;
    private javax.swing.JLabel studentsLabel;
    private javax.swing.JList<String> studentsList;
    private javax.swing.JScrollPane studentsListScrollPane;
    private javax.swing.JLabel viewerWindowLabel;
    // End of variables declaration
}
